### ISSUE TITLE
FS.RemoveDir does not handle exclusion pattern for files

### ISSUE THREAD

**Issue by vansha** [yevhen/Nake#12]
I've followed this example from [Nake.csx](https://github.com/yevhen/Nake/blob/bb05a4dbb9ebd8300af0d567b17cd2d4cb2271d3/Nake.csx#L30):
```csharp
RemoveDir(@"**\bin|**\obj|{path}\*|-:*.vshost.exe");    
```

Expecting that folders containing `*.vshost.exe` files (presumably locked by VS) would not be removed.
However Nake tries to remove them according to this message:

```
Removing directory "C:\projects\..\someproj\bin".
MSBUILD : error MSB3231: Unable to remove directory "C:\projects\..\someproj\bin". Access to the path SomeProj.vshost.exe' is denied.
Microsoft.Build.Tasks.RemoveDir failed
```

Probably such exclusion for files should not be used with `RemoveDir`, as it is not really consistent with FileSet exclusion semantics. But on the other hand, such exclusion looks very handy. So I'm not sure whether it worth it to fix behavior. Or it's better to fix `Nake.csx` instead :)

Other possible approach could be adding a standard `ContinueOnError` msbuild parameter to the `RemoveDir` extension.

**Comment by yevhen** [comment]
Looks like it's a typo (bloody Ctrl-C\Ctrl-V :)

I'm not sure whether it's possible to actually fix it. Both `FileSet` and `RemoveDir` behave as expected. Excluding folders containing _files_ that match an exclusion pattern is an additional semantics for `FileSet` that I've never thought about, since It doesn't fit normal globbing rules.

**Comment by vansha** [comment]
Yep, I understand that. It worth fixing Nake.csx then to avoid confusion.

PS. I've work-arounded it by simply wrapping RemoveDir in a try-catch block.

**Comment by yevhen** [comment]
I'll fix script to not confuse ppl.
