### ISSUE TITLE
how to debug a nake script (csx file) in visual studio

### ISSUE THREAD

**Issue by yevgenchepurko** [yevhen/Nake#17]
Hi Yevhen,

I trust you are well!
Could you please suggest is there a way to debug a nake script in visual studio?
There doesn't seem to be any info available on this in net.

Any info would be mach appreciated.
Thanks in advance.

PS:
There is some link how to debug csx files with scriptcs.exe:
https://github.com/scriptcs/scriptcs/wiki/Debugging-a-script
but it doesn't seem to be helpful with nake scripts, when you don't even have scriptcs.exe on your PC, but have nake package, and using nake.exe instead of scriptcs.exe as per this instruction doesn't seem to be helpful.

**Comment by yevhen** [comment]
Sure, you can do it. Let me get back to you a little bit later. Tonight 😄

**Comment by vansha** [comment]
First of all, I'd like to mention that I've never tried to debug Nake scripts before, as there were no such need. Good old `Trace("debug message")` always did their job.

Anyway there is a way to debug a script in a VisualStudio. I've just tried to do it in following way.

Create a separate VS solution similar to this one - https://github.com/yevhen/Nake/blob/5c33068a535dfb6eeed9dc2ba4db5dca23815ed5/Tools/Nake/Debug.sln. The easiest way is to actually copy that text and edit accordingly:

* `Executable = C:\Work\Nake\Tools\Nake\Nake.exe` - path to the Nake tool
* `StartingDirectory = C:\Work\Nake\` - path to the directory containing script to debu.
* `Arguments = --debug build` arguments to the `Nake.exe`

**Comment by yevgenchepurko** [comment]
Thanks @vansha, the solution you've suggested works like a charm!

Trace("debug message") it's a good one when you write a new piece of code, but when you learn someone else's code, debugging is a very valuable option. 

And it's a pleasure to hear from you, it's a small village, isn't it :)

**Comment by yevhen** [comment]
Cool, thanks @vansha :)
