### ISSUE TITLE
Spaces in directory confuses params passed to MSBuild

### ISSUE THREAD

**Issue by andyhoyle** [yevhen/Nake#18]
>MSBUILD : error MSB1008: Only one project can be specified.
>Switch: Samples\Orleankka\Output;ReferencePath=C:\Users\a\Code
>
>For switch syntax, type "MSBuild /help"
>Process exited with code 1

Actual directory name was "Code Samples"

**Comment by yevhen** [comment]
Could you pls give more context? Also, have you tried to put the value in quotes?

**Comment by andyhoyle** [comment]
Sorry, I was running the following command from the root of Orleankka project from the command line:
> nake Build

**Comment by andyhoyle** [comment]
I have just checked and this is a bug in the Nake.csx in Orleankka not in Nake.
