### ISSUE TITLE
Running on .NET Core

### ISSUE THREAD

**Issue by yevhen** [yevhen/Nake#4]
In principle, it should be relatively easy to run Nake on Mono using Xamarin's version of Roslyn, but Utility library requires more serious effort. In order to have faster TTM, Utility library was built on top of MSBuild, so a lot of built-in functions such as those in FS class need to be rewritten using only .NET apis. 

Similar situation is with MSBuild function. Mono uses it's own XBuild engine, to build .NET projects. It's compatible with MSBuild project format and possibility of hosting it within Nake (like MSBuild) need to be investigated. Or layer of indirection should be created.

For the rest, some minor stuff which uses native Win32 calls should be done with conditional compilation. For the whole list, MOMA could be used.

**Comment by Nate-Wilkins** [comment]
@yevhen so I'm rewriting the FS class right now for the .NET apis and I'm settling on similar syntax to node's [child_process](https://nodejs.org/api/child_process.html). 

Something like this
```
using static Nake.Run;
using static Nake.Log;

Exec("echo hello", (error, stdout, stderr) => 
{
    if (error != null) throw error;
    Log.Out(stdout);
});

var echo = Spawn("echo", ["hello"]);

echo.Stdout += (data) => Lot.Out(data);
echo.Stderr += (data) => Log.Out(data);
echo.OnExit += (code) => Log.Out($"Exited with {code}");
```

What do you think? I can't really use the MSBuild libraries for core :( I don't really think they're worth keeping around.

**Comment by Nate-Wilkins** [comment]
And to be honest `Process.Start` could be used for `Spawn` instead. 
I do find some value in `Exec` but not much, mostly just syntax improvement.

**Comment by dadhi** [comment]
@Nate-Wilkins, sorry for amateur question, if I am wrong, please ignore.

Is FS refers to File System?

If so, can you utilize @xoofx [zio](https://github.com/xoofx/zio)?

**Comment by yevhen** [comment]
Ye, MSBuild was chosen as a quick solution to get up and running but we need to find good substitute for it. 

@dadhi Zio looks promising

**Comment by yevhen** [comment]
Fixed by https://github.com/yevhen/Nake/pull/23 😄
